### PR TITLE
Fix/ignore all PHPStan problems

### PR DESCRIPTION
**Pull request by szepeviktor**
@Spomky Watch out! I don't know what I'm doing. ⚠️

### CODE REVIEW

**Comment by szepeviktor** [comment]
Oh noooo!
@Spomky

**Comment by Spomky** [comment]
Hi,

No worries I will take this PR into consideration.
I just need more time to define a clear road for it and the next major release.

**Comment by Spomky** [comment]
Hi,

I close this Pr as it is now imported in the new branch v4.0.
THank you for your help, this looks much more clear now!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request closed without merging**
