### PR TITLE
Custom Exceptions

### PR DESCRIPTION
**Pull request by Spomky**
Target branch: 
Resolves issue # 

- [ ] It is a Bug fix
- [x] It is a New feature
- [ ] Breaks BC
- [ ] Includes Deprecations

### CODE REVIEW

**Comment by TimWolla** [comment]
FYI: This change actually breaks BC, because `AuthenticatorAttestationResponseValidator` no longer throws `InvalidArgumentException`, but `AuthenticatorResponseVerificationException` which does not inherit from InvalidArgumentException, thus any catch blocks that catch `InvalidArgumentException` will no longer catch.

I recommend the following:

1. Convert `WebauthnException` into an interface. You can catch interfaces in a catch block!
2. Make `AuthenticatorResponseVerificationException` extend `InvalidArgumentException`.

**Comment by TimWolla** [comment]
Also:

`PublicKeyCredentialLoader::load()` throws the original `JsonException`. It might be useful to create a dedicated library-specific Exception that wraps the JsonException using `$previous`.

**Comment by Spomky** [comment]
😬
Oops. Sorry for that. I had in mind that try/catch blocks rely directly on `\Throwable`, not any particular exception. What if `WebauthnException` extends `InvalidArgumentException`?

**Comment by TimWolla** [comment]
> Oops. Sorry for that. I had in mind that try/catch blocks rely directly on `\Throwable`, not any particular exception

Already fixed my app to catch `WebauthnException` instead and also to catch the JsonException from the loader, was enough enough :smiley: 

> What if `WebauthnException` extends `InvalidArgumentException`?

I don't this is the right choice, because not every WebauthnException is an InvalidArgumentException. Consider the case where the HTTP request for Android SafetyNet validation fails. You likely want to throw a `WebauthnException` there, but that one clearly isn't an InvalidArgumentException!

Instead the SafetyNet validation failure might be something like:

```
class NetworkValidationFailed extends \Exception implements WebauthnException { }
```

**Pull request merged**
