### PR TITLE
Allow php8 and test against it on CI

### LINKED ISSUE #164: Php 8 compatibility
**Is your feature request related to a problem? Please describe.**

Nextcloud is preparing for php8. We're looking at our dependencies and make sure we update/fix the ones that are not ready for php8. ``web-auth/webauthn-lib`` is one of them.

**Describe the solution you'd like**

Fix any php8 incompatibility and declare php8 as compatible via composer.

**Describe alternatives you've considered**

n/a

**Additional context**

n/a

### PR DESCRIPTION
**Pull request by ChristophWurst**
Fixes https://github.com/web-auth/webauthn-framework/issues/164

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Oh, Travis doesn't run for pull requests.

**Comment by Spomky** [comment]
Hi @ChristophWurst,

Thank you for this PR.
Actually, [the v3.3](https://github.com/web-auth/webauthn-framework/tree/v3.3) adresses this issue.
It should be released in early January 2021

**Comment by ChristophWurst** [comment]
That is good news. I checked your wrong default branch apparently.

**Comment by ChristophWurst** [comment]
> Thank you for this PR.
> Actually, [the v3.3](https://github.com/web-auth/webauthn-framework/tree/v3.3) adresses this issue.
> It should be released in early January 2021

Hey @Spomky do you have a rough idea for when the release will be done? I don't mean to sound impatient or anything, but we'll soon release a new major version of Nextcloud and I'd love to have the lib updated ASAP. If there's anything we can help with, please let me know :v:

**Pull request closed without merging**
