### PR TITLE
Fix syntax error in Makefile

### LINKED ISSUE #266: nproc command does not produce output in CI
### Version(s) affected

5.0.x

### Description

https://github.com/web-auth/webauthn-framework/blob/05d74f3e3ae7d328cc51cc806ac212d3659a2cbe/Makefile#L40

### How to reproduce

```
$ nproc
```

on my server it outputs `4` with user permissions (no root)

### Possible Solution

I do not know!!

### Additional Context

kép

### PR DESCRIPTION
**Pull request by szepeviktor**
# 🤯

Fixes #266

### CODE REVIEW

**Comment by szepeviktor** [comment]
I was working so hard on `nproc` but the problem is here.

**Comment by Spomky** [comment]
Aside the fact that you are doing a really hard work on this repository (!), it is also an interesting issue.
I noted that Rector takes approx. 1min30 when it only takes few seconds on my computer.
Engines are not the same, but it looks like [the `parallel` option](https://github.com/web-auth/webauthn-framework/blob/4.2.x/rector.php#L34) is not working as well.

**Comment by szepeviktor** [comment]
> takes few seconds on my computer.

`vendor/bin/rector process --ansi --dry-run --xdebug`

kép

Do you have xdebug enabled also?

**Comment by szepeviktor** [comment]
Now 6 minutes instead of 9 minutes!

**Pull request merged**
