### PR TITLE
Verify origin's host

### PR DESCRIPTION
**Pull request by davispuh**
| Q             | A
| ------------- | ---
| Branch?       | v1.1
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no

See [determines the set of origins on which the public key credential may be exercised](https://www.w3.org/TR/webauthn/#determines-the-set-of-origins-on-which-the-public-key-credential-may-be-exercised)

> The RP ID must be equal to the origin's effective domain, or a registrable domain suffix of the origin's effective domain.

This PR implements matching against registrable domain suffix.

To use this feature need to provide a callable that can return registrable domain. eg `www.google.com` to `google.com`

[PHP Domain Parser](https://github.com/jeremykendall/php-domain-parser) provides one such implementation.
```php
$manager = new \Pdp\Manager(new \Pdp\Cache(), new  \Pdp\CurlHttpClient());
$rules = $manager->getRules();
$registrableDomainResolver = function ($domain) use ($rules) { return $rules->resolve($domain)->getRegistrableDomain(); };

$publicKeyCredentialCreationOptions = new PublicKeyCredentialCreationOptions(
    $rpEntity,
    $userEntity,
    $challenge,
    $publicKeyCredentialParametersList,
    $timeout,
    $excludedPublicKeyDescriptors,
    $authenticatorSelectionCriteria,
    PublicKeyCredentialCreationOptions::ATTESTATION_CONVEYANCE_PREFERENCE_NONE,
    $extensions,
    $registrableDomainResolver
);
```

### CODE REVIEW

**Comment by Spomky** [comment]
Hi,

Thank you for this PR. I don't understand why but the CI failed.
Anyway I am not a big fan of it and let me explain why.

The data to check is the origin set by the RP in the response (`$C->getOrigin()`). This value is compared (strictly) to either the `rpId` (if set by the developer) or the domain in the current request object.
As we already trust the `rpId` or the domain from the request, we don't need to check if the data in response is an acceptable relaying party ID. The only reason for this to fail is that the `rpId` set by the developer is an incorrect value.

The only remain check is the scheme. I removed this assertion because it is not needed.
No relaying party shall communicate with compatible devices if the connection is not secured. This is an rp requirement. Moreover, none of the `origin` value sent by devices contain the scheme and this check will undoubtedly fail.

**Comment by davispuh** [comment]
> The data to check is the origin set by the RP in the response ($C->getOrigin()). This value is compared (strictly) to either the rpId (if set by the developer) or the domain in the current request object.
> As we already trust the rpId or the domain from the request, we don't need to check if the data in response is an acceptable relaying party ID. The only reason for this to fail is that the rpId set by the developer is an incorrect value.

You're only partially right and indeed it can be implemented better so I just updated this PR. We can't always strictly compare origin to `rpId`. Because suppose I have domains `accounts.google.com` and `drive.google.com` and I want to authenticate to both using same authenticator so I set `rpId` to `google.com` but now when we'll receive origin domain from browser it will be actual host like `drive.google.com` which won't match our `rpId` so the reason for that check to fail isn't because of incorrect value :stuck_out_tongue: 

> Moreover, none of the origin value sent by devices contain the scheme and this check will undoubtedly fail.

That's not true, I tested it with Firefox 65 and Chromium 72 and both sent `scheme` as `https`

**Comment by Spomky** [comment]
Hi,

That’s right this won’t work if in the `PublicKeyCredentialCreationOptions` we use `example.com` and if the assertion/attestation comes from `subdomain.example.com`.

I added a test to cover that. I will send an update soon.

By the way you are right the scheme is part of the origin. To avoid any BC break I let it unchecked at the moment but will introduce it in the next major release or as an option.

**Comment by Spomky** [comment]
Closing as now integrated in the v1.1 branch.
Thank you for it. I will mention this issue in the v1.1 release note.

**Comment by davispuh** [comment]
> Closing as now integrated in the v1.1 branch.
> Thank you for it. I will mention this issue in the v1.1 release note.

To me it looks like there's a mistake.

```php
        $clientDataRpId = $parsedRelyingPartyId['host'];
        Assertion::notEmpty($clientDataRpId, 'Invalid origin rpId.');
        $rpIdLength = mb_strlen($rpId);
        // this looks like it doesn't do anything, shouldn't it be mb_substr($clientDataRpId, -$rpIdLength) ?
        Assertion::eq(mb_substr($rpId, -$rpIdLength), $rpId, 'rpId mismatch.');
```

**Pull request closed without merging**
