### PR TITLE
Disable coverage in CI

### PR DESCRIPTION
**Pull request by szepeviktor**
| Q             | A
| ------------- | ---
| Branch?       |
| Bug fix?      | 
| New feature?  | 
| BC breaks?    | 
| Deprecations? |

### CODE REVIEW

**Comment by szepeviktor** [comment]
But not for Infection :(

> Coverage needs to be generated but no code coverage generator (pcov, phpdbg  
   or xdebug) has been detected.

**Comment by szepeviktor** [comment]
> The minimum required MSI percentage should be 33%, but actual is 32.47%. Improve your tests!

It wasn't me.

**Comment by Spomky** [comment]
>It wasn't me.

Ah ah ah! No worries. I increased from 22 to 33 but 30 should be fine.
The way the estimate is computed is strange. Depending on the platform the result can be different of 1 or 2%.

**Comment by szepeviktor** [comment]
All green 🍏

**Comment by Spomky** [comment]
From ~12min to less than 6 now!
Not bad for a Thursday night.
Many thanks for the help 👍🏽.

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
