### PR TITLE
Wrong service call

### LINKED ISSUE #216: Symfony 6 - Dependency on a non-existent service "Webauthn\MetadataService\MetadataStatementRepository"
**Describe the bug**
After install on symfony 6, error "Dependency on a non-existent service"

**To Reproduce**
`composer require web-auth/webauthn-symfony-bundle`

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome 100

Trace :
```
PS C:\Users\thoma\OneDrive\Documents\Developpement web\Sites web\lebackoffice> composer require web-auth/webauthn-symfony-bundle 
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^4.0 for web-auth/webauthn-symfony-bundle
./composer.json has been updated
Running composer update web-auth/webauthn-symfony-bundle
Loading composer repositories with package information
Updating dependencies
Lock file operations: 15 installs, 0 updates, 0 removals
  - Locking brick/math (0.9.3)
  - Locking fgrosse/phpasn1 (v2.4.0)
  - Locking league/uri (6.5.0)
  - Locking league/uri-interfaces (2.3.0)
  - Locking nyholm/psr7 (1.5.0)
  - Locking php-http/message-factory (v1.0.2)
  - Locking spomky-labs/cbor-bundle (v3.0.0)
  - Locking spomky-labs/cbor-php (v3.0.0)
  - Locking symfony/psr-http-message-bridge (v2.1.2)
  - Locking web-auth/cose-lib (v4.0.1)
  - Locking web-auth/metadata-service (v4.0.1)
  - Locking web-auth/webauthn-lib (v4.0.1)
  - Locking web-auth/webauthn-symfony-bundle (v4.0.1)
  - Locking web-token/jwt-core (v3.0.3)
  - Locking web-token/jwt-signature (v3.0.3)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 15 installs, 0 updates, 0 removals
  - Downloading league/uri-interfaces (2.3.0)
  - Downloading php-http/message-factory (v1.0.2)
  - Downloading spomky-labs/cbor-php (v3.0.0)
  - Downloading fgrosse/phpasn1 (v2.4.0)
  - Downloading web-auth/cose-lib (v4.0.1)
  - Downloading league/uri (6.5.0)
  - Downloading web-auth/metadata-service (v4.0.1)
  - Downloading web-token/jwt-core (v3.0.3)
  - Downloading web-token/jwt-signature (v3.0.3)
  - Downloading web-auth/webauthn-lib (v4.0.1)
  - Downloading symfony/psr-http-message-bridge (v2.1.2)
  - Downloading spomky-labs/cbor-bundle (v3.0.0)
  - Downloading nyholm/psr7 (1.5.0)
  - Downloading web-auth/webauthn-symfony-bundle (v4.0.1)
  - Installing league/uri-interfaces (2.3.0): Extracting archive
  - Installing php-http/message-factory (v1.0.2): Extracting archive
  - Installing brick/math (0.9.3): Extracting archive
  - Installing spomky-labs/cbor-php (v3.0.0): Extracting archive
  - Installing fgrosse/phpasn1 (v2.4.0): Extracting archive
  - Installing web-auth/cose-lib (v4.0.1): Extracting archive
  - Installing league/uri (6.5.0): Extracting archive
  - Installing web-auth/metadata-service (v4.0.1): Extracting archive
  - Installing web-token/jwt-core (v3.0.3): Extracting archive
  - Installing web-token/jwt-signature (v3.0.3): Extracting archive
  - Installing web-auth/webauthn-lib (v4.0.1): Extracting archive
  - Installing symfony/psr-http-message-bridge (v2.1.2): Extracting archive
  - Installing spomky-labs/cbor-bundle (v3.0.0): Extracting archive
  - Installing nyholm/psr7 (1.5.0): Extracting archive
  - Installing web-auth/webauthn-symfony-bundle (v4.0.1): Extracting archive
Generating optimized autoload files
108 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

Symfony operations: 3 recipes (871d82372587a6717346391dc673626d)
  - Configuring spomky-labs/cbor-bundle (>=v3.0.0): From auto-generated recipe
  - Configuring nyholm/psr7 (>=1.0): From github.com/symfony/recipes:master
  -  WARNING  web-auth/webauthn-symfony-bundle (>=3.0): From github.com/symfony/recipes-contrib:master
    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Review the recipe at https://github.com/symfony/recipes-contrib/tree/master/web-auth/webauthn-symfony-bundle/3.0

    Do you want to execute this recipe?
    [y] Yes
    [n] No
    [a] Yes for all packages, only for the current installation session
    [p] Yes permanently, never ask again for this project
    (defaults to n): y
  - Configuring web-auth/webauthn-symfony-bundle (>=3.0): From github.com/symfony/recipes-contrib:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!  
!!    The service "Webauthn\AuthenticatorAttestationResponseValidator" has a dependency on a non-existent service "Webauthn\MetadataService\MetadataStatementRepository".  
!!  
!!
!!
Script @auto-scripts was called via post-update-cmd
```

### PR DESCRIPTION
**Pull request by Spomky**
Fixes #216

### CODE REVIEW

**Comment by szepeviktor** [comment]
@Spomky Do you plan to add a unit test for this?

**Comment by Spomky** [comment]
Hi @szepeviktor,

This is right that the compiler passes are not fully tested. Only during the kernel boot and with one fully featured configuration.
So yes tests could be added to prevent regressions.

**Comment by Spomky** [comment]
Hi @szepeviktor,

Tests have been added for all Compiler Passes.
See https://github.com/web-auth/webauthn-framework/commit/d124cbafadfb413973facb9565f0f7dfe130d1c0

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
