### PR TITLE
Improve PR template

### PR DESCRIPTION
**Pull request by szepeviktor**
from Larastan
Please see diff!

### CODE REVIEW

**Comment by Spomky** [comment]
This is a good idea to change it.
Do you know if it is possible to create one in YAML? The [doc page](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) is mute about that

**Comment by szepeviktor** [comment]
AFAIK these templates are plain text files.
After the PR is created GitHub renders the user-edited content.

**Comment by szepeviktor** [comment]
Target branch: wrench 🔧 
Resolves issue #000

- [ ] It is a Bug fix
- [x] It is a New feature
- [ ] Breaks BC
- [x] Includes Deprecations

**Comment by szepeviktor** [comment]
What you want is Issue Forms for PR-s
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
... but there is no such a thing.

**Comment by Spomky** [comment]
> What you want is Issue Forms for PR-s

This is excatly what I was looking for, but it does not seem to be available.
Anyway, this one looks good to me

**Pull request merged**
