### PR TITLE
feat: add packages required for serialization

### PR DESCRIPTION
**Pull request by joostdebruijn**
Target branch: 4.8.0
Resolves issue: n/a

- [ ] It is a Bug fix
- [x] It is a New feature
- [ ] Breaks BC
- [ ] Includes Deprecations

Those packages are required to make the serializer work.

### CODE REVIEW

**Comment by Spomky** [comment]
Hi,

😅 I missed these dependencies.
They are also needed in [MetadataStatementSerializerFactory](https://github.com/web-auth/webauthn-framework/blob/4.8.x/src/metadata-service/src/Denormalizer/MetadataStatementSerializerFactory.php#L7-L9).

**Comment by joostdebruijn** [comment]
@Spomky Thanks for merging this one! However, the `web-auth/webauthn-lib` sub repository doesn't have the Symfony serializer related packages now (also not in the suggest)? I'm using that sub repo for my own implementation in the Laravel-framework, however the three Symfony serializer related packages are necessary for parsing the authenticator responses for example. Shouldn't they be added as suggested package at least?

**Comment by Spomky** [comment]
No worries, it is automatically split and tagged on release

**Comment by joostdebruijn** [comment]
@Spomky Hm, I'm using v4.8.1 now and when only requiring `web-auth/webauthn-lib`, the symfony serializer packages must be installed separately.

**Comment by joostdebruijn** [comment]
The package `phpdocumentor/reflection-docblock` should be added as dependency well as I discovered in production where my dev dependencies are not installed. 😅

**Pull request merged**
