### PR TITLE
U2F support

### PR DESCRIPTION
**Pull request by jirkasemmler**
Fixing U2F support. 
1. The key has to be transformed to COSE key 
2. rpIdHash is asserted to origin if it is u2f type

### CODE REVIEW

**Comment by Spomky** [comment]
Excellent! Many thanks

**Comment by ChristophWurst** [comment]
@Spomky may I kindly ask if it would be possible to get this fix released as a patch release (v3.3.11?)?

**Comment by Spomky** [comment]
Done. Tagged as `v3.3.12`.
Lany thanks for your help

**Comment by Spomky** [comment]
Hi @jirkasemmler and @ChristophWurst,

I noted that the `appid` extension and this patch are not correctly covered by tests.
Would it be possible to have sample data for adding some test cases?

Many thanks.
Regards.

**Pull request merged**
